### ISSUE TITLE
Wrong data send

### ISSUE THREAD

**Issue by Benji1992-HU** [bertmelis/esp32ModbusRTU#11]
Hy!
I tryed to use your libary on Heltec Wifi kit 32. 
I modifyed the example code:
``` 
#include <Arduino.h>
#include <esp32ModbusRTU.h>
#include <algorithm>  // for std::reverse

#define TIMEOUT_MS 3000
#define QUEUE_SIZE 20

esp32ModbusRTU modbus(&Serial1, 16);  // use Serial1 and pin 16 as RTS

void setup() {
  pinMode(12,OUTPUT);
  Serial.begin(115200);  // Serial output
  Serial1.begin(19200, SERIAL_8N1, 17, 5, true);  // Modbus connection



  modbus.onData(handleData);
  modbus.onError([](esp32Modbus::Error error) {
    Serial.printf("error: 0x%02x\n\n", static_cast<uint8_t>(error));
  });
  modbus.begin();

}

void loop() {
  static uint32_t lastMillis = 0;
  if (millis() - lastMillis > 7000) {
    lastMillis = millis();
    Serial.print("sending Modbus request...\n");
    modbus.readHoldingRegisters(0x01, 1, 1);
  }
}

void handleData(uint8_t serverAddress, esp32Modbus::FunctionCode fc, uint8_t* data, size_t length) {
  Serial.printf("received data: id: %u, fc %u\ndata: 0x", serverAddress, fc);
  for (uint8_t i = 0; i < length; ++i) {
    Serial.printf("%02x", data[i]);
  }
  Serial.print("\n");
}
```

The hardware connection is the following:
ESP32 modul ------> MAX485 module ------> RS485 to USB coverter ------> PC

On the PC I use the "Modbus Slave" software.[https://www.modbustools.com/modbus_slave.html](url)
When I estabilish the connection, on the PC in Communication trafic monitor I see this(attached picture)
![modbus_error](https://user-images.githubusercontent.com/47895802/66580459-ba914500-eb7e-11e9-90e3-29f33383207c.PNG)
It is not an valid modbus data. What is wrong with my code?
Thanks and best regards!
Benji

**Comment by bertmelis** [comment]
Swapped A and B? Connected wrong pins?
Do you have the latest Arduino core?

**Comment by bertmelis** [comment]
wait, your first byte is 7F and should be 01. Swap A and B...

See https://en.wikipedia.org/wiki/RS-485#Signals
It's not always clear.

**Comment by Benji1992-HU** [comment]
I swapped the A and B pins. The Slave address and function code is ok but the register start address, quantity and CRC is not.
![modbus_trafic](https://user-images.githubusercontent.com/47895802/66696659-27ffbb80-ecce-11e9-9b6b-218b78054af4.PNG)

I know the esp is 3.3V logic, but the MAX485  does not work at that level?

**Comment by bertmelis** [comment]
MAX485 has 5V logic. I tried it myself without succes. I also tried MAX3485 from Aliexpress and eBay with mixed results. In the end I bought MAX3485 from a thrustworty shop and all my issues we're gone.

So, try with a 3.3V driver or use a level converter in between.

**Comment by Benji1992-HU** [comment]
Thanks! I try it asap and I am applying for the result.

**Comment by Benji1992-HU** [comment]
Hy!
I tryed with other esp (NodeMCU-32S) and an original MAX481 ic with level shifter and the result is the same...
![modbus_error_2](https://user-images.githubusercontent.com/47895802/67080239-136f6780-f195-11e9-9649-f2218bea4f48.PNG)

When i swap the A-B line the result is the following:
![modbus_error_3](https://user-images.githubusercontent.com/47895802/67081041-b4aaed80-f196-11e9-8573-7bd1cf11921e.PNG)

I tried with MAX481 and other arduino board(UNO) and libary and the modbus work good.

**Comment by Benji1992-HU** [comment]
Finaly I found the problem. In the modbus slave software I dont set the parity to none.
Thanks!
