### ISSUE TITLE
custom modbus request

### ISSUE THREAD

**Issue by EmanueleFeola** [bertmelis/esp32ModbusRTU#45]
How can I implement with the library a request like this?
![image](https://user-images.githubusercontent.com/22152406/94824376-3f671580-0405-11eb-9222-6b7318f92453.png)

**Comment by bertmelis** [comment]
This is not a modbus message format.

While it should not be a big problem implementing this in this lib, it is very specific and out of scope.

**Comment by EmanueleFeola** [comment]
For now, I came up with this, but I can't understand what to assign to _byteCount
Can you please give me a hint?

![image](https://user-images.githubusercontent.com/22152406/94899751-20639480-0494-11eb-9a98-e0ce6c8ce28d.png)

**Comment by bertmelis** [comment]
`_byteCount` is used to calculate the length of the response message (and add the CRC into the right location).

I don't know what type of response you get when using this message.

**Comment by EmanueleFeola** [comment]
This is the response I get.
So should _byteCount be 6? 

![image](https://user-images.githubusercontent.com/22152406/94900922-2195c100-0496-11eb-80c9-412a907fafc7.png)

**Comment by EmanueleFeola** [comment]
I wrote the function without using the library, problem solved
