### ISSUE TITLE
RS232 Question

### ISSUE THREAD

**Issue by Tsaadon** [bertmelis/esp32ModbusRTU#49]
Hello everyone,
I was wondering if this library could also work with RS232 communication or is it only for RS485? and if it does not, could you give me any quick guidance on how to read data from a sensor communicating in RS232?
Thanks,
Tal.

**Comment by bertmelis** [comment]
In fact, this library is completely unaware of the actual interface. It does use the UART hardware of your ESP but if you connect that one directly to your device, over RS485 or RS232 doesn't matter.

It is however up to you -in your code- to setup Serial using the correct parameters (baud, bits, invert...)

**Comment by Tsaadon** [comment]
Ok great,  thanks for the info.
